import { Lang } from './content';

export const UI: Record<Lang, Record<string, string>> = {
  fr: {
    navExpertise: 'Expertise',
    navProjects: 'Projets',
    navSectors: 'Secteurs',
    navAbout: 'À propos',
    navMentoring: 'Mentorat',
    navTestimonials: 'Avis clients',
    navContact: 'Contact',
    reviewCta: 'Laisser un avis',
    talkProjectCta: 'Parler d’un projet',
    heroEyebrow: 'Software Engineer • SaaS & Systems Builder',
    heroTitle: 'Je construis des produits digitaux qui font avancer les entreprises.',
    heroLead: 'De la stratégie au déploiement, je conçois des plateformes web, applications mobiles, SaaS et systèmes internes pensés pour de vrais enjeux business.',
    heroExplore: 'Découvrir mes réalisations',
    heroTalk: 'Parler d’un projet',
    heroCardCity: 'Basée à Kénitra, au Maroc',
    heroCardProjects: '25+ projets et entreprises accompagnées',
    heroCardLangs: 'Français • English • العربية',
    statCompanies: 'Entreprises & projets accompagnés',
    statLanguages: 'Langues de travail',
    statCity: 'Basée à Kénitra, Maroc',
    statReach: 'Maroc & international',
    logoBandLabel: 'Ils m’ont fait confiance',
    projectsEyebrow: 'Projets sélectionnés',
    projectsTitle: 'Des réalisations concrètes, pensées pour l’impact.',
    viewProject: 'Voir le projet',
    viewCaseStudy: 'Voir l’étude de cas',
    exploreAllProjects: 'Voir tous mes projets',
    projectsPageEyebrow: 'Tous mes projets',
    projectsPageTitle: 'Une collection de produits, plateformes et expériences digitales.',
    loadMoreProjects: 'Voir plus de projets',
    backToProjects: '← Retour aux projets',
    previousProject: 'Projet précédent',
    nextProject: 'Projet suivant',
    caseProjectTitle: 'Le projet',
    caseAchievementsTitle: 'Ce qui a été réalisé',
    caseInterventionLabel: 'Mon intervention',
    caseVisitSite: 'Voir le site',
    caseBookCall: 'Réserver un appel découverte',
    sectorsEyebrow: 'Secteurs',
    sectorsTitle: 'Des solutions pensées pour votre activité.',
    expertiseEyebrow: 'Expertise',
    expertiseTitle: 'Des solutions digitales adaptées à vos ambitions.',
    aboutEyebrow: 'À propos',
    aboutTitle: 'Technique. Stratégique. Impliquée.',
    aboutName: 'Njimate Aicha',
    aboutPositioning: 'Développeuse Web, Mobile & SaaS · Fondatrice de FalconDeev · Consultante Freelance 1:1 · Tech Speaker',
    aboutText1: 'J’aide les entrepreneurs, marques et entreprises à transformer leurs idées en solutions digitales performantes : sites web modernes, applications mobiles, plateformes SaaS et systèmes internes.',
    aboutText2: 'À travers FalconDeev, j’accompagne les startups, cabinets, e-commerces et PME à lancer, structurer et faire évoluer leur présence digitale. Je propose également des consultations freelance 1:1 autour du positionnement, des offres, du pricing, de l’acquisition client et de la carrière tech. J’interviens également dans des écoles et événements tech en tant que speaker.',
    falconCta: 'Découvrir FalconDeev',
    bookConsultationCta: 'Réserver une consultation',
    mentoringLabel: 'Mentorat • Speaking • Transmission',
    mentoringTitle: 'Accompagner les idées jusqu’à leur transformation en projets.',
    mentoringIntro: 'Mentor en entrepreneuriat digital et intervenante tech, j’accompagne les porteurs de projets dans la structuration de leurs idées et je partage mon expérience auprès des étudiants et des communautés professionnelles.',
    talksEyebrow: 'Tech Speaker',
    talksTitle: 'Interventions',
    testimonialsEyebrow: 'Avis clients',
    testimonialsTitle: 'Leur confiance, ma meilleure preuve.',
    contactEyebrow: 'Contact',
    contactTitle: 'Créons quelque chose de fort.',
    contactAvailability: 'Disponible au Maroc et à l’international',
    contactCardEmailAction: 'Envoyer un e-mail',
    contactCardWhatsappAction: 'Discuter sur WhatsApp',
    contactCardInstagramAction: 'Voir le profil',
    contactCardLinkedinAction: 'Voir le profil',
    themeToggleLabel: 'Changer de thème',
    contactFormName: 'Nom',
    contactFormEmail: 'Email',
    contactFormCompany: 'Entreprise',
    contactFormWebsite: 'Site actuel (si existant)',
    contactFormProjectType: 'Type de projet',
    contactFormBudget: 'Budget indicatif',
    contactFormLaunchDate: 'Date de lancement souhaitée',
    contactFormMessage: 'Message',
    contactFormSubmit: 'Envoyer ma demande',
    contactFormSending: 'Envoi en cours…',
    contactSuccess: 'Merci ! Votre demande a bien été envoyée. Je vous répondrai dans les meilleurs délais.',
    contactError: 'Une erreur est survenue. Merci de réessayer ou de m’écrire directement par email.',
    contactFormEyebrow: 'Option 1 · Formulaire',
    calendlyEyebrow: 'Option 2 · Consultation',
    calendlyBlockText: 'Vous préférez en parler directement ? Réservez un appel découverte gratuit de 30 minutes.',
    calendlyBlockCta: 'Réserver un appel de 30 minutes',
    reviewModalTitle: 'Laisser un avis',
    reviewFormName: 'Nom du client',
    reviewFormCompany: 'Entreprise ou projet',
    reviewFormEmail: 'Email (non publié)',
    reviewFormRating: 'Note de 1 à 5',
    reviewFormMessage: 'Témoignage',
    reviewFormConsent: 'J’autorise la publication de mon avis (nom et entreprise affichés, email jamais publié).',
    reviewSubmit: 'Envoyer',
    reviewSending: 'Envoi en cours…',
    reviewSent: 'Merci pour votre avis. Il sera vérifié avant sa publication.',
    reviewError: 'Une erreur est survenue. Merci de réessayer.',
    filterAll: 'Tous',
    missingImageLabel: 'Visuel à venir',
    closeModal: 'Fermer'
  },
  en: {
    navExpertise: 'Expertise',
    navProjects: 'Projects',
    navSectors: 'Industries',
    navAbout: 'About',
    navMentoring: 'Mentoring',
    navTestimonials: 'Reviews',
    navContact: 'Contact',
    reviewCta: 'Leave a review',
    talkProjectCta: 'Talk about a project',
    heroEyebrow: 'Software Engineer • SaaS & Systems Builder',
    heroTitle: 'I build digital products that Mehdi-Taxibusinesses forward.',
    heroLead: 'From strategy to deployment, I design web platforms, mobile apps, SaaS products and internal systems built for real business challenges.',
    heroExplore: 'Explore my projects',
    heroTalk: 'Talk about a project',
    heroCardCity: 'Based in Kénitra, Morocco',
    heroCardProjects: '25+ projects and companies supported',
    heroCardLangs: 'French • English • Arabic',
    statCompanies: 'Companies & projects supported',
    statLanguages: 'Working languages',
    statCity: 'Based in Kénitra, Morocco',
    statReach: 'Morocco & international',
    logoBandLabel: 'They trusted me',
    projectsEyebrow: 'Selected projects',
    projectsTitle: 'Concrete work, built for real impact.',
    viewProject: 'View project',
    viewCaseStudy: 'View case study',
    exploreAllProjects: 'Explore all projects',
    projectsPageEyebrow: 'All my projects',
    projectsPageTitle: 'A collection of products, platforms and digital experiences.',
    loadMoreProjects: 'Load more projects',
    backToProjects: '← Back to projects',
    previousProject: 'Previous project',
    nextProject: 'Next project',
    caseProjectTitle: 'The project',
    caseAchievementsTitle: 'What was delivered',
    caseInterventionLabel: 'My involvement',
    caseVisitSite: 'Visit site',
    caseBookCall: 'Book a discovery call',
    sectorsEyebrow: 'Industries',
    sectorsTitle: 'Solutions shaped around your business.',
    expertiseEyebrow: 'Expertise',
    expertiseTitle: 'Digital solutions built around your ambitions.',
    aboutEyebrow: 'About',
    aboutTitle: 'Technical. Strategic. Hands-on.',
    aboutName: 'Njimate Aicha',
    aboutPositioning: 'Web, Mobile & SaaS Developer · Founder of FalconDeev · 1:1 Freelance Consultant · Tech Speaker',
    aboutText1: 'I help entrepreneurs, brands and companies turn their ideas into high-performing digital solutions: modern websites, mobile apps, SaaS platforms and internal systems.',
    aboutText2: 'Through FalconDeev, I help startups, firms, e-commerces and SMEs launch, structure and grow their digital presence. I also offer 1:1 freelance consulting on positioning, offers, pricing, client acquisition and tech careers. I also speak at schools and tech events.',
    falconCta: 'Discover FalconDeev',
    bookConsultationCta: 'Book a consultation',
    mentoringLabel: 'Mentoring • Speaking • Transmission',
    mentoringTitle: 'Helping ideas evolve into viable digital projects.',
    mentoringIntro: 'As a digital entrepreneurship mentor and tech speaker, I help project owners structure their ideas while sharing practical experience with students and professional communities.',
    talksEyebrow: 'Tech Speaker',
    talksTitle: 'Talks',
    testimonialsEyebrow: 'Testimonials',
    testimonialsTitle: 'Their trust, my best proof.',
    contactEyebrow: 'Contact',
    contactTitle: 'Let’s build something strong.',
    contactAvailability: 'Available in Morocco and internationally',
    contactCardEmailAction: 'Send an email',
    contactCardWhatsappAction: 'Chat on WhatsApp',
    contactCardInstagramAction: 'View profile',
    contactCardLinkedinAction: 'View profile',
    themeToggleLabel: 'Switch theme',
    contactFormName: 'Name',
    contactFormEmail: 'Email',
    contactFormCompany: 'Company',
    contactFormWebsite: 'Current website (if any)',
    contactFormProjectType: 'Project type',
    contactFormBudget: 'Indicative budget',
    contactFormLaunchDate: 'Target launch date',
    contactFormMessage: 'Message',
    contactFormSubmit: 'Send my request',
    contactFormSending: 'Sending…',
    contactSuccess: 'Thank you! Your request has been sent successfully. I’ll get back to you as soon as possible.',
    contactError: 'Something went wrong. Please try again or email me directly.',
    contactFormEyebrow: 'Option 1 · Form',
    calendlyEyebrow: 'Option 2 · Consultation',
    calendlyBlockText: 'Prefer to discuss it directly? Book a free 30-minute discovery call.',
    calendlyBlockCta: 'Book a 30-minute call',
    reviewModalTitle: 'Leave a review',
    reviewFormName: 'Client name',
    reviewFormCompany: 'Company or project',
    reviewFormEmail: 'Email (not published)',
    reviewFormRating: 'Rating from 1 to 5',
    reviewFormMessage: 'Testimonial',
    reviewFormConsent: 'I authorize publication of my review (name and company shown, email never published).',
    reviewSubmit: 'Send',
    reviewSending: 'Sending…',
    reviewSent: 'Thank you for your review. It will be verified before publication.',
    reviewError: 'Something went wrong. Please try again.',
    filterAll: 'All',
    missingImageLabel: 'Visual coming soon',
    closeModal: 'Close'
  }
};
